name: socialai
description: "ZW - AI-powered mobile app aggregation and summarization platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  shared_preferences: ^2.2.2
  dio: ^5.7.0
  connectivity_plus: ^5.0.2
  fl_chart: ^0.65.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  supabase_flutter: ^2.9.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  device_apps: ^2.2.0
  device_info_plus: ^10.1.0
  package_info_plus: ^5.0.1
  app_settings: ^5.1.1
  share_plus: ^8.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  tflite_flutter: ^0.10.4
  image: ^4.1.7
  http: ^1.2.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  carousel_slider: ^4.2.1
  photo_view: ^0.14.0
  timeago: ^3.6.1

  web: any
  record: ^6.0.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/